//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        public Jugadores()
        {
            this.SancionesJugador = new HashSet<SancionesJugador>();
        }
    
        public int idJugador { get; set; }
        public Nullable<int> idEquipo { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<int> Altura { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<int> Puntos { get; set; }
        public Nullable<int> Partidos_Jugados { get; set; }
        public Nullable<int> Partidos_Ganados { get; set; }
        public Nullable<int> Partidos_Perdidos { get; set; }
        public Nullable<int> Partidos_Empatados { get; set; }
        public Nullable<int> TarjetasAmarillas { get; set; }
        public Nullable<int> TarjetasRojas { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual ICollection<SancionesJugador> SancionesJugador { get; set; }
    }
}
