//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligas
    {
        public Ligas()
        {
            this.Equipos = new HashSet<Equipos>();
            this.Partidos = new HashSet<Partidos>();
        }
    
        public int idLiga { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idCategoriaLiga { get; set; }
    
        public virtual Categoria_Ligas Categoria_Ligas { get; set; }
        public virtual ICollection<Equipos> Equipos { get; set; }
        public virtual ICollection<Partidos> Partidos { get; set; }
    }
}
