//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanciones_Equipo
    {
        public int idSancion_Equipo { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> multa { get; set; }
        public Nullable<int> idCategoria_Sancion { get; set; }
        public Nullable<int> idEquipo { get; set; }
    
        public virtual CategoriasSanciones CategoriasSanciones { get; set; }
        public virtual Equipos Equipos { get; set; }
    }
}
