//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campos
    {
        public Campos()
        {
            this.Partidos = new HashSet<Partidos>();
        }
    
        public int idCampo { get; set; }
        public Nullable<int> idClub { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<Partidos> Partidos { get; set; }
    }
}
