//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasSanciones
    {
        public CategoriasSanciones()
        {
            this.Sanciones_Equipo = new HashSet<Sanciones_Equipo>();
            this.SancionesJugador = new HashSet<SancionesJugador>();
        }
    
        public int idCategoriaSancion { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Sanciones_Equipo> Sanciones_Equipo { get; set; }
        public virtual ICollection<SancionesJugador> SancionesJugador { get; set; }
    }
}
