//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadisticasPartidos
    {
        public int idEstadistica_Partido { get; set; }
        public int idPartido { get; set; }
        public int idEquipo { get; set; }
        public Nullable<int> Ensayos { get; set; }
        public Nullable<int> Conversiones { get; set; }
        public Nullable<int> GolpesCastigo { get; set; }
        public Nullable<int> Drops { get; set; }
        public Nullable<int> TarjetasAmarillas { get; set; }
        public Nullable<int> TarjetasRojas { get; set; }
        public int Marcador { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Partidos Partidos { get; set; }
    }
}
